[package]
authors = ["The Rust Project Developers"]
name = "alloc"
version = "0.0.0"
autotests = false
autobenches = false
edition = "2018"

[lib]
name = "alloc"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }
compiler_builtins = { path = "../compiler_builtins" }
